name: Scraper Altura Río La Plata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar script de Node.js
        # Aquí le inyectamos de forma segura los secretos a nuestro script
        env:
          TELEFONO: ${{ secrets.TELEFONO }}
          API_KEY: ${{ secrets.API_KEY }}
        run: node index.js
